language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
install:
- sudo apt-get install -y curl tar
- curl https://raw.githubusercontent.com/apex/apex/master/install.sh | sudo sh
- pip install -r requirements.txt -t functions/convert
- pip install coveralls
script: coverage run setup.py test
after_success: coveralls
deploy:
- provider: script
  skip_cleanup: true
  script: "apex deploy"
  on:
    branch: master
    python: '2.7'
env:
  global:
  - secure: Jw3KVGdmgqWlVkiPBYcCCwUF6RqNWwKZ1vpH0T4P7nHSIjpYau3JR6fDw4WkJeVBOcE9H232LN1MpIH4nWlJ6fu5jigu/qDWqZlRXU79NtyMbFizfXFGLBXfr113PqfCp2mosiC44QFku0G/cBN7w57JRL1mn9KLSGxfHwvXd3BVA290yV4IFz+8RPvjp34N/3kWHk00UH/XW1FEkVC2wUiVIo6pbSVRXeYwmLGqqqqQp+rX75z4OPwtVfu6j86cEfmkn6UK5ZSPiyl8M3SVLCG9XfClPlh05G4h9pDjlA7Gkqx1+Q3xDGR74d3QQ6Kvmod+u6IVEnafpdq44OUadBR5ByAeZyV+3gO+b4DhZvpLxw8C3DtWTYVATKDInUMQkU+XXe40L/QGvvQ8HhWtkYA1U6cR1+oeUPSOB0+cBEnQezHnBgv9IapiNT16IPkEtnttOwGBXdw9giXTwjWh/xlmbRS7tgoVydCJ8msmkoo2W/9fHFwXejvnp11kvWabPHO8t+9wLwa8fasj8uN4Eqk4SemfE9hOc+O846OUIUmaeXhNvhL0erNkeax5qEwbq5iLcwE/C90G5L5BzlLPHuLlD3X2x1OxlZA/cjCBIJ06rh71BjE0TogcAfLhiCIA9hjI+AqBJDulGv1fxBpZgq/O942HS7Z9pURkhACNgU4=
  - secure: JJ/3x4n/tMQsxzOGIDWgaLHr/KGXOewZqR25tTMvh+YgTs/pUCfgo6RV9DrJUbp0SOd5cBSDtbV0xuKQTkVhbM7SYZMpW3dew7Q7Sm51r6za/J0r2l7R4XFldL3l2do6j4XE5ORL5ZH1NaGzEqdIW/l0zfef/9wJYsJcSE5bFVaZYQl927CDTqFawBYqus312mjPmBQ7IQgGH0XptTQi2E1NoM6myB2zwx2NxFQ4aOIRaCPh9L8sYyvCpTLnP7uBSEvYBa8ruaYaUVmcdECOG3U1FGOfLSowIV3q/MAcRe8zgJzW7Pi+oFsfOuovlnvvnhjZFM+LW1YBR/k1KUe4cyWhFfoMflAGGFjDWMBT2KlNd8pnq2E3qp/gHUeoe1yzp5sBAeQznOliv3G82+NHvYIVYZXb5M4Q9kdc1Be3o49giarInIKphHM6u3YS8eDB11nA7Jk/LR07TH/0fZ1zOEPT8OJjZVK91dDGBbsRIsKfxAwvFc5ocuXb+zlplFD2WBzthdVkC2J/j/CvzSI+7XdLqtraIeqzPo3yNs8SCRiONTGYSoCyEtfvruiwcBtRzoioAq7nJRpNqHBemcJ6WxF5OO9za330vKVWndMUphOQaLYrDzKUCLTwYA0mx7b883fA4XjjLfTnFwWBRIzgBAoUnVEBG4+t8p4SPLRtUdE=
  - secure: ifojQDwTrn1VB2yOuc//hKYzTBfF7ik2USsruT2mE6lnhrD8H+SHfmYPLNPvfG4cwC+bSRCjTg0J8t34xsb9TZjVQ6cJyqleI4jzzgtOgHbr7UFKVMKWZc1sSopFzPgOs61d8sOyQJbjLjK89CAniKGcbTOso9CzNmFt/2H+sBTLaxqAx0UQ7sOdc59G3lUDRoBUnOaaZRtKxHjK0W8Xv4UZl0fAp0JUG/qmwnx6ouq13dJA6tjZaRTIX38QWx16j2M7uTwN4Yx9Rn1IXRaoXan7S50VaqdQI8rfC6uMNl+oeiBO1glzXvrBG+tqVgbEnx3/Ryp8Nnejk8Owep+YQNe2qtt6Kwhyjkm1e3D4JzpK9J51Pn0CvfcYuX0lm2tJkXpd2Z9v/HU8cFuZ2bTc4YUR+dpW4ep16L86iNmG02S8GA8ToXtLChVyEZqjSZg33qo0Y7cgAT0+0p0Cj2aPpQeoOPF8pm/WsJtF1wwC4rhzKoBb3XEHkkmR/hy+z+6yS62LVZkkq+DDGbvUqdJ7ke0vXXYoUEWVM/1MFAshDDB/ZQaituayTihV4ylaqcIOEwlFzt0EuQwQYeHfYcABhicknMirrwFf+Ckj/GFMWqChoWkxa0/0XCqJaIo+avO6yp9i7WUI7wp+gxHXVUB8+BehxxnVd2lfCxxXXSxgT74=
